import mongoose, { Document, Schema, Types } from 'mongoose';

export enum ChatRole {
    USER = 'user',
    ASSISTANT = 'assistant',
}

export interface IChatMessage {
    role: ChatRole;
    content: string;
    type: 'text' | 'image' | 'voice' | 'system';
    mimetype?: string;
    createdAt: Date;
}

export interface IChatSessionDB extends Document {
    repairRequestId: Types.ObjectId;
    customerId: Types.ObjectId;
    messages: IChatMessage[];
    isFinished: boolean;
    /** Bullet-point report generated by AI after chat ends */
    aiReport: string[];
    createdAt: Date;
    updatedAt: Date;
}

const chatMessageSchema = new Schema<IChatMessage>(
    {
        role: {
            type: String,
            required: true,
            enum: Object.values(ChatRole),
        },
        content: {
            type: String,
            required: true,
        },
        type: {
            type: String,
            required: true,
            enum: ['text', 'image', 'voice', 'system'],
            default: 'text',
        },
        mimetype: {
            type: String,
            required: false,
        },
        createdAt: {
            type: Date,
            default: () => new Date(),
        },
    },
    { _id: false, strict: true },
);

const chatSessionSchema = new Schema<IChatSessionDB>(
    {
        repairRequestId: {
            type: Schema.Types.ObjectId,
            ref: 'RepairRequest',
            required: true,
        },
        customerId: {
            type: Schema.Types.ObjectId,
            ref: 'Customer',
            required: true,
        },
        messages: {
            type: [chatMessageSchema],
            default: [],
        },
        isFinished: {
            type: Boolean,
            default: false,
        },
        aiReport: {
            type: [String],
            default: [],
        },
    },
    {
        timestamps: true,
        strict: true,
    },
);

chatSessionSchema.index({ repairRequestId: 1 });
chatSessionSchema.index({ customerId: 1 });

const ChatSessionModel =
    mongoose.models.ChatSession ||
    mongoose.model<IChatSessionDB>('ChatSession', chatSessionSchema);

export default ChatSessionModel;
