export interface ManufacturerData {
  name: string;
  models: string[];
  defaultPlatform: string;
}

export interface CategoryData {
  name: string;
  manufacturers: ManufacturerData[];
}

export const DEVICE_DATA: Record<string, CategoryData> = {
  Smartphones: {
    name: 'Smartphones',
    manufacturers: [
      {
        name: 'Apple',
        defaultPlatform: 'ios',
        models: [
          'iPhone 17 Pro Max', 'iPhone 17 Pro', 'iPhone 17 Plus', 'iPhone 17',
          'iPhone 16 Pro Max', 'iPhone 16 Pro', 'iPhone 16 Plus', 'iPhone 16',
          'iPhone 15 Pro Max', 'iPhone 15 Pro', 'iPhone 15 Plus', 'iPhone 15',
          'iPhone 14 Pro Max', 'iPhone 14 Pro', 'iPhone 14 Plus', 'iPhone 14',
          'iPhone 13 Pro Max', 'iPhone 13 Pro', 'iPhone 13', 'iPhone 13 mini',
          'iPhone 12 Pro Max', 'iPhone 12 Pro', 'iPhone 12', 'iPhone 12 mini',
          'iPhone 11 Pro Max', 'iPhone 11 Pro', 'iPhone 11',
          'iPhone SE (3rd Gen)', 'iPhone SE (2nd Gen)', 'iPhone XR',
        ],
      },
      {
        name: 'Samsung',
        defaultPlatform: 'android',
        models: [
          'Galaxy S26 Ultra', 'Galaxy S26+', 'Galaxy S26',
          'Galaxy S25 Ultra', 'Galaxy S25+', 'Galaxy S25',
          'Galaxy S24 Ultra', 'Galaxy S24+', 'Galaxy S24', 'Galaxy S24 FE',
          'Galaxy S23 Ultra', 'Galaxy S23+', 'Galaxy S23', 'Galaxy S23 FE',
          'Galaxy Z Fold7', 'Galaxy Z Flip7',
          'Galaxy Z Fold6', 'Galaxy Z Flip6',
          'Galaxy Z Fold5', 'Galaxy Z Flip5',
          'Galaxy Z Fold4', 'Galaxy Z Flip4',
          'Galaxy A56', 'Galaxy A55', 'Galaxy A54',
          'Galaxy A36', 'Galaxy A35', 'Galaxy A34',
          'Galaxy A25', 'Galaxy A24', 'Galaxy A15', 'Galaxy A14',
          'Galaxy M55', 'Galaxy M35', 'Galaxy M15',
          'Galaxy XCover 7',
        ],
      },
      {
        name: 'Xiaomi',
        defaultPlatform: 'android',
        models: [
          'Xiaomi 15 Ultra', 'Xiaomi 15 Pro', 'Xiaomi 15',
          'Xiaomi 14 Ultra', 'Xiaomi 14 Pro', 'Xiaomi 14',
          'Xiaomi 13 Ultra', 'Xiaomi 13 Pro', 'Xiaomi 13',
          'Xiaomi 14T Pro', 'Xiaomi 14T', 'Xiaomi 13T Pro', 'Xiaomi 13T',
          'Redmi Note 14 Pro+', 'Redmi Note 14 Pro', 'Redmi Note 14',
          'Redmi Note 13 Pro+', 'Redmi Note 13 Pro', 'Redmi Note 13',
          'Redmi Note 12 Pro', 'Redmi Note 12',
          'Poco F6 Pro', 'Poco F6', 'Poco F5 Pro', 'Poco F5',
          'Poco X6 Pro', 'Poco X6', 'Poco X5 Pro',
          'Poco M6 Pro',
          'Xiaomi Mix Fold 4', 'Xiaomi Mix Flip',
        ],
      },
      {
        name: 'OPPO',
        defaultPlatform: 'android',
        models: [
          'Find X8 Pro', 'Find X8',
          'Find X7 Ultra', 'Find X7',
          'Find X6 Pro', 'Find X6',
          'Find N4 Fold', 'Find N4 Flip',
          'Find N3', 'Find N3 Flip',
          'Reno 12 Pro', 'Reno 12',
          'Reno 11 Pro', 'Reno 11',
          'Reno 10 Pro+', 'Reno 10 Pro', 'Reno 10',
          'F27 Pro+', 'F27', 'F25 Pro', 'F23',
          'A3 Pro', 'A79', 'A78', 'A59', 'A58', 'A38',
          'K12', 'K11', 'K10',
        ],
      },
      {
        name: 'vivo',
        defaultPlatform: 'android',
        models: [
          'X200 Pro', 'X200', 'X100 Ultra', 'X100 Pro', 'X100',
          'X90 Pro+', 'X90 Pro', 'X90',
          'X Fold3 Pro', 'X Fold3', 'X Fold2', 'X Flip',
          'V30 Pro', 'V30', 'V30e',
          'V29 Pro', 'V29', 'V29e',
          'V27 Pro', 'V27',
          'T3', 'T3x', 'T2 Pro', 'T2',
          'Y200e', 'Y200', 'Y100', 'Y56', 'Y36', 'Y28',
        ],
      },
      {
        name: 'Infinix',
        defaultPlatform: 'android',
        models: [
          'Zero 40 Pro', 'Zero 40',
          'Zero 30 5G', 'Zero 30 4G',
          'Note 40 Pro+', 'Note 40 Pro', 'Note 40',
          'Note 30 VIP', 'Note 30 Pro', 'Note 30',
          'Hot 40 Pro', 'Hot 40', 'Hot 40i',
          'Smart 8 Plus', 'Smart 8',
        ],
      },
      {
        name: 'Tecno',
        defaultPlatform: 'android',
        models: [
          'Phantom V Fold 2', 'Phantom V Flip 2',
          'Phantom V Fold', 'Phantom V Flip',
          'Phantom X2 Pro', 'Phantom X2',
          'Camon 30 Premier', 'Camon 30 Pro', 'Camon 30',
          'Camon 20 Premier', 'Camon 20 Pro',
          'Spark 20 Pro+', 'Spark 20 Pro', 'Spark 20',
          'Pova 6 Pro',
        ],
      },
      {
        name: 'Realme',
        defaultPlatform: 'android',
        models: [
          'GT 6 Pro', 'GT 6', 'GT 5 Pro', 'GT 5',
          'GT Neo 6', 'GT Neo 6 SE',
          'Realme 13 Pro+', 'Realme 13 Pro', 'Realme 13',
          'Realme 12 Pro+', 'Realme 12 Pro', 'Realme 12',
          'C67', 'C65', 'C55',
        ],
      },
      {
        name: 'Huawei',
        defaultPlatform: 'android',
        models: [
          'Mate 70 Pro+', 'Mate 70 Pro', 'Mate 70',
          'Pura 70 Ultra', 'Pura 70 Pro', 'Pura 70',
          'Mate 60 Pro', 'Mate 60',
          'Mate X5', 'Mate X3', 'Pocket 2',
          'Nova 12 Ultra', 'Nova 12 Pro', 'Nova 12',
          'Enjoy 70',
        ],
      },
      {
        name: 'Google',
        defaultPlatform: 'android',
        models: [
          'Pixel 10 Pro XL', 'Pixel 10 Pro', 'Pixel 10',
          'Pixel 9 Pro XL', 'Pixel 9 Pro', 'Pixel 9', 'Pixel 9 Pro Fold',
          'Pixel 8 Pro', 'Pixel 8', 'Pixel 8a',
          'Pixel 7 Pro', 'Pixel 7', 'Pixel 7a',
          'Pixel Fold', 'Pixel 6 Pro', 'Pixel 6', 'Pixel 6a',
          'Pixel 5', 'Pixel 5a 5G',
        ],
      },
      {
        name: 'OnePlus',
        defaultPlatform: 'android',
        models: [
          'OnePlus 13', 'OnePlus 13R',
          'OnePlus 12', 'OnePlus 12R',
          'OnePlus 11', 'OnePlus 10 Pro', 'OnePlus 10T',
          'OnePlus 9 Pro', 'OnePlus 9',
          'Nord 4', 'Nord CE 4', 'Nord CE 4 Lite',
          'Nord 3', 'Nord CE 3',
        ],
      },
    ],
  },

  Laptops: {
    name: 'Laptops',
    manufacturers: [
      {
        name: 'Apple',
        defaultPlatform: 'macos',
        models: [
          'MacBook Pro 16-inch (M4 Max)', 'MacBook Pro 16-inch (M4 Pro)',
          'MacBook Pro 14-inch (M4 Max)', 'MacBook Pro 14-inch (M4 Pro)', 'MacBook Pro 14-inch (M4)',
          'MacBook Air 15-inch (M4)', 'MacBook Air 13-inch (M4)',
          'MacBook Pro 16-inch (M3 Max)', 'MacBook Pro 16-inch (M3 Pro)',
          'MacBook Pro 14-inch (M3 Max)', 'MacBook Pro 14-inch (M3 Pro)', 'MacBook Pro 14-inch (M3)',
          'MacBook Air 15-inch (M3)', 'MacBook Air 13-inch (M3)',
          'MacBook Pro 16-inch (M2 Max)', 'MacBook Pro 16-inch (M2 Pro)',
          'MacBook Pro 14-inch (M2 Max)', 'MacBook Pro 14-inch (M2 Pro)', 'MacBook Pro 13-inch (M2)',
          'MacBook Air 15-inch (M2)', 'MacBook Air 13-inch (M2)',
          'MacBook Pro 16-inch (M1 Max)', 'MacBook Pro 16-inch (M1 Pro)',
          'MacBook Pro 14-inch (M1 Max)', 'MacBook Pro 14-inch (M1 Pro)', 'MacBook Pro 13-inch (M1)',
          'MacBook Air 13-inch (M1)',
          'MacBook Pro 16-inch (Intel, 2019)', 'MacBook Pro 15-inch (Intel)', 'MacBook Pro 13-inch (Intel)',
          'MacBook Air 13-inch (Intel)',
        ],
      },
      {
        name: 'Lenovo',
        defaultPlatform: 'windows',
        models: [
          'ThinkPad X1 Carbon Gen 13', 'ThinkPad X1 Carbon Gen 12',
          'ThinkPad X1 Yoga Gen 9',
          'ThinkPad T14 Gen 5', 'ThinkPad T14s Gen 5', 'ThinkPad T16 Gen 3',
          'ThinkPad P1 Gen 7', 'ThinkPad P16 Gen 2',
          'ThinkPad E14 Gen 6', 'ThinkPad E16 Gen 2',
          'Legion Pro 7i Gen 9', 'Legion Pro 5i Gen 9',
          'Legion 7i Gen 9', 'Legion 5i Gen 9', 'Legion Slim 5 Gen 9',
          'Yoga Pro 9i Gen 9', 'Yoga Pro 7i Gen 9',
          'Yoga 9i 2-in-1 Gen 9', 'Yoga 7i 2-in-1 Gen 9',
          'IdeaPad Pro 5i', 'IdeaPad Slim 5i', 'IdeaPad Slim 3i', 'IdeaPad Flex 5i',
          'LOQ 15IRX9', 'LOQ 16',
          'ThinkBook 16p Gen 5', 'ThinkBook 14 Gen 6', 'ThinkBook 15 Gen 5',
        ],
      },
      {
        name: 'HP',
        defaultPlatform: 'windows',
        models: [
          'Spectre x360 14', 'Spectre x360 16',
          'OMEN Transcend 16', 'OMEN Transcend 14', 'OMEN 17', 'OMEN 16',
          'Victus 16', 'Victus 15',
          'Envy x360 16', 'Envy x360 14', 'Envy 17', 'Envy 16',
          'Pavilion Aero 13', 'Pavilion Plus 16', 'Pavilion Plus 14', 'Pavilion 15', 'Pavilion x360 14',
          'Dragonfly G4',
          'EliteBook 840 G11', 'EliteBook 860 G11', 'EliteBook 1040 G11',
          'ProBook 440 G11', 'ProBook 450 G11',
          'ZBook Studio G11', 'ZBook Firefly G11', 'ZBook Power G11', 'ZBook Fury G11',
          'OmniBook Ultra 14',
        ],
      },
      {
        name: 'Dell',
        defaultPlatform: 'windows',
        models: [
          'XPS 16', 'XPS 15', 'XPS 14', 'XPS 13', 'XPS 17',
          'Alienware m18 R2', 'Alienware m16 R2',
          'Alienware x16 R2', 'Alienware x14 R2',
          'G16 Gaming Laptop', 'G15 Gaming Laptop',
          'Inspiron 16 Plus', 'Inspiron 14 Plus',
          'Inspiron 16 2-in-1', 'Inspiron 14 2-in-1', 'Inspiron 15',
          'Latitude 9450 2-in-1', 'Latitude 7650', 'Latitude 7450',
          'Latitude 5550', 'Latitude 5450', 'Latitude 3550', 'Latitude 3450',
          'Precision 7780', 'Precision 7680', 'Precision 5690', 'Precision 5490', 'Precision 3590',
          'Vostro 16', 'Vostro 15',
        ],
      },
      {
        name: 'ASUS',
        defaultPlatform: 'windows',
        models: [
          'ROG Zephyrus G16', 'ROG Zephyrus G14', 'ROG Zephyrus Duo 16',
          'ROG Strix SCAR 18', 'ROG Strix SCAR 16', 'ROG Strix G18', 'ROG Strix G16',
          'ROG Flow X16', 'ROG Flow X13', 'ROG Flow Z13',
          'TUF Gaming A16', 'TUF Gaming A15', 'TUF Gaming F16', 'TUF Gaming F15',
          'Zenbook Duo (2024)', 'Zenbook 14 OLED', 'Zenbook S 13 OLED',
          'Zenbook Pro 16X OLED', 'Zenbook Pro 14 Duo OLED', 'Zenbook 14X OLED',
          'Vivobook Pro 16X OLED', 'Vivobook Pro 15 OLED',
          'Vivobook S 16 OLED', 'Vivobook S 14 OLED', 'Vivobook 16X', 'Vivobook 15X',
          'ExpertBook B9 OLED', 'ExpertBook B5',
          'ProArt P16', 'ProArt PX13',
        ],
      },
      {
        name: 'Acer',
        defaultPlatform: 'windows',
        models: [
          'Predator Helios 18', 'Predator Helios 16', 'Predator Helios Neo 16',
          'Nitro 17', 'Nitro 16', 'Nitro V 15',
          'Swift X 14', 'Swift Edge 16', 'Swift Go 14', 'Swift 3',
          'Aspire 7', 'Aspire 5', 'Aspire 3',
          'Chromebook Spin 714', 'Chromebook Plus 515',
        ],
      },
      {
        name: 'MSI',
        defaultPlatform: 'windows',
        models: [
          'Titan 18 HX', 'Raider GE78 HX', 'Raider GE68 HX', 'Vector 16 HX',
          'Stealth 18 AI Studio', 'Stealth 16 Studio', 'Stealth 14 Studio',
          'Pulse 17', 'Katana 15', 'Cyborg 15',
          'Creator Z17 HX Studio', 'Creator M16',
          'Prestige 16 AI Evo', 'Summit E16 Flip', 'Modern 15',
        ],
      },
      {
        name: 'Microsoft',
        defaultPlatform: 'windows',
        models: [
          'Surface Laptop 7th Edition', 'Surface Pro 11th Edition',
          'Surface Laptop Studio 2',
          'Surface Laptop 6 for Business', 'Surface Pro 10 for Business',
          'Surface Laptop Go 3', 'Surface Go 4',
          'Surface Pro 9', 'Surface Laptop 5',
          'Surface Studio 2+', 'Surface Laptop 4', 'Surface Pro 8',
          'Surface Laptop Go 2', 'Surface Go 3', 'Surface Pro X',
        ],
      },
      {
        name: 'Samsung',
        defaultPlatform: 'windows',
        models: [
          'Galaxy Book4 Ultra', 'Galaxy Book4 Pro 360', 'Galaxy Book4 Pro',
          'Galaxy Book4 360', 'Galaxy Book4',
          'Galaxy Book3 Ultra', 'Galaxy Book3 Pro 360', 'Galaxy Book3 Pro',
          'Galaxy Book3 360', 'Galaxy Book3',
          'Galaxy Book2 Pro 360', 'Galaxy Book2 Pro', 'Galaxy Book2 360',
          'Galaxy Book Go',
        ],
      },
      {
        name: 'Huawei',
        defaultPlatform: 'windows',
        models: [
          'MateBook X Pro (2024)', 'MateBook X Pro (2023)',
          'MateBook 16s', 'MateBook 14s',
          'MateBook 14 (2024)', 'MateBook 14 (2023)',
          'MateBook D 16 (2024)', 'MateBook D 16 (2023)',
          'MateBook D 14 (2024)', 'MateBook D 14 (2023)',
          'MateBook E (2023)', 'MateBook E Go',
          'MateBook 13s',
        ],
      },
    ],
  },
};
